// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// FindOutstanding provides a mock function with given fields: writer, req
func (_m *Controller) FindOutstanding(writer http.ResponseWriter, req *http.Request) {
	_m.Called(writer, req)
}

// Payment provides a mock function with given fields: writer, req
func (_m *Controller) Payment(writer http.ResponseWriter, req *http.Request) {
	_m.Called(writer, req)
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
