// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	loan "gitlab.com/2024/Juni/amartha-billing-srv2/application/loan"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// FetchOutstanding provides a mock function with given fields: ctx, uid
func (_m *Service) FetchOutstanding(ctx context.Context, uid string) (*loan.FetchOutstandingResponse, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for FetchOutstanding")
	}

	var r0 *loan.FetchOutstandingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*loan.FetchOutstandingResponse, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *loan.FetchOutstandingResponse); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*loan.FetchOutstandingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Payment provides a mock function with given fields: ctx, paymentRequest
func (_m *Service) Payment(ctx context.Context, paymentRequest *loan.PaymentRequest) error {
	ret := _m.Called(ctx, paymentRequest)

	if len(ret) == 0 {
		panic("no return value specified for Payment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *loan.PaymentRequest) error); ok {
		r0 = rf(ctx, paymentRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
